### ISSUE TITLE
The scale of "broadened intensities" should be independent of calculator (`SpinWaveTheory` or `dynamical_correlations`)

### ISSUE THREAD

**Issue by kbarros** [SunnySuite/Sunny.jl#264]
At the moment, the dynamical structure factor calculated by `intensities_broadened` has a scale that depends on the numerical calculation method: `SpinWaveTheory` or `dynamical_correlations`.

Concretely, `SpinWaveTheory` reports intensities as $S(q,\omega)$, while classical dynamics reports intensities as $S(q,\omega) \Delta\omega$. In other words, only the SWT calculation is truly a "density" in energy space. Note that, for classical dynamics, the finite energy bin width $\Delta \omega$ will scale like the inverse trajectory length.

Changes to the intensity scale are _breaking_, because they will modify every plot that has a manually tuned `colorrange`. Nonetheless, I think we should unify the intensity scale in Sunny 0.6. After informally polling Sunny developers, there seems to be a general consensus that  $S(q,\omega)$ (a density in energy space) is the right choice, because $\Delta \omega$ is an arbitrary artifact of the numerical calculation.

(Incidentally, SpinW uses the $S(q,\omega) \Delta \omega$ convention, which would be an argument to go in the opposite direction.)

**Comment by Lazersmoke** [comment]
There are two ways to compute "broadened intensities" from either the spin wave, or the classical calculation: binned or interpolated.

The behavior of the interpolated option (which is what this issue is about) should be S(q,w). So this issue is specifically referring to `intensities_broadened(:: SamplesCorrelations,...)` which may or may not be implemented at the time of writing.

The behavior of the binned option should be S(q,w) integrated over the bin (which is approximately but not exactly S(q,w) Delta omega Delta q, where Delta omega is the binwidth in BinningParameters, NOT the classical trajectory energy resolution, which is an arbitrary computational artifact as mentioned). And this should (also) match between classical-binned and spinwave-binned.

**Comment by kbarros** [comment]
Fixed in #272.
